# Test urls
login_url: 'https://test-stand.gb.ru/gateway/login'
posts_url: 'https://test-stand.gb.ru/api/posts'
profile_url: 'https://test-stand.gb.ru/gateway/users/profile/'

# Auth data
username: 'Gris'
password: '2575a9ed0d'

# Data in post
username_in_post: 'testtest1'

## Create post
title: test_title
description: test_description
content: test_content
description_answer: test_description